### ISSUE TITLE
No action when using search box

### ISSUE THREAD

**Issue by jayneerc** [froid1911/aavegotchi-xp-dashboard#2]
Whenever I enter any valid gotchi ID, clicking Search performs no action.
Produces a number of similar errors in chrome devtools console eg
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'aavegotchi')
    at index-d1107d00a5d38b45d92a.js:1:1983
    at l (main-3471f9e78cb3bb918a47.js:1:72006)
    at Generator._invoke (main-3471f9e78cb3bb918a47.js:1:71794)
    at Generator.next (main-3471f9e78cb3bb918a47.js:1:72435)
    at r (415-6d7fb1c5867bb418ee34.js:1:37576)
    at a (415-6d7fb1c5867bb418ee34.js:1:37779)

**Comment by froid1911** [comment]
gm @jayneerc and thanks for the issue. its fixed.

**Comment by jayneerc** [comment]
Brilliant - thanks!
